steps:
  # Paso 1: Construye la imagen de Docker y súbela a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sociuslab-api', '.']

  # Paso 2: Empuja (push) la imagen al Container Registry de Google Cloud
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sociuslab-api']

  # Paso 3: Despliega la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'nombre-de-tu-api',
           '--image', 'gcr.io/$PROJECT_ID/tu-api',
           '--region', 'us-central1',    # Cambia la región si prefieres otra
           '--platform', 'managed',
           '--allow-unauthenticated']

# Opcional: Define las imágenes que quieres conservar (de no hacerlo, se elimina por defecto después de 6 meses)
images:
  - 'gcr.io/$PROJECT_ID/tu-api'
